### ISSUE TITLE
Inclusion of this neat (not really) bitmap on the example

### ISSUE THREAD

**Issue by xspager** [rgbkrk/bitjet#14]
``` python
b'\x00\x00\x00\x00\x00\x00\x00\x78\x01\xE0\x00\x00\x00\x00\x78\x01\xE0\x01\xF8\x00\x00\x78\x01\xE7\x81\xF8\x00\x30\x78\x00\x07\x80\x18\x00\x30\x78\x00\x07\x80\x18\x00\x30\x79\xE1\xEF\xF0\x18\x7C\x7E\x7F\xF1\xEF\xF0\x18\xFE\x7E\x7F\xF1\xEF\xF0\x19\x87\x30\x78\xF9\xE7\x80\x1B\x03\x30\x78\x79\xE7\x80\x1B\xFF\x30\x78\x79\xE7\x80\x1B\xFF\x30\x78\x79\xE7\x80\x1B\x00\x30\x78\x79\xE7\x80\x1B\x00\x30\x78\xF9\xE7\x80\x1B\x80\x30\x7F\xF1\xE7\xF4\x39\xC1\x30\x7F\xE1\xE3\xF7\xF0\xFF\x3E\x7F\xC1\xE1\xF7\xE0\x7E\x1E\x00\x00\x00\x00\x00\x00\x00'
```

![captura de tela 2015-02-24 as 03 12 10](https://cloud.githubusercontent.com/assets/802840/6344158/739c73c0-bbd3-11e4-8bf4-4f185a05efd2.png)
![captura de tela 2015-02-24 as 03 12 30](https://cloud.githubusercontent.com/assets/802840/6344159/77b9b710-bbd3-11e4-9bb1-3151f611b40d.png)

**Comment by rgbkrk** [comment]
Wow! That's wonderful.

I think we'll have to make that the official logo! How did you make it? That's really cool.

Wonder if there's a way to make the logo appear when viewed as hex too. Perhaps if it was made at a higher "resolution", so that when you divide by 8 it's at a decent size?

**Comment by xspager** [comment]
I made a grayscale PNG with Gimp, then used imagemagic to convert to a monochromatic .pbm file, then used hexdump to generate the python hex string:

``` bash
$ convert image.png -monochrome image.pbm # ImageMagic command
$ hexdump -s 9 -v -e '"\\\x" 1/1 "%02X"' image.pbm # skip the header and dump a PBM image as a Python hex string
```

**Comment by rgbkrk** [comment]
I hereby dub you bitslinger.

I'm happy if you put this in `bitjet/__init__.py` as `__logo__ = b'\x00\x00\x00\x00\x00\x00\x00\x78...`

**Comment by rgbkrk** [comment]
Now that it's included as `bitjet.__logo__` and the example notebook, I'd say we're good to go. Thanks again @xspager!
