### ISSUE TITLE
Install procedure

### ISSUE THREAD

**Issue by xspager** [rgbkrk/bitjet#9]
Hi, loved the extension :) I had some trouble getting it to run. Had to install the IPython RC1 and to list manually its dependencies, also needed to install numpy to get the example to work. So:

pip install ipython==3.0.0rc1 jsonschema tornado jinja2 pyzmq numpy
python setup.py install

**Comment by rgbkrk** [comment]
Yeah, I was thinking numpy would be an optional dependency as standalone bytes work just fine. Not sure how to handle that part of packaging.

You're absolutely right that it needs the IPython 3 release candidate. I'm actually working off of master in preparation for the coming release.

I'm happy if you want to supply instructions for install.

In particular, the instructions should read:

```
pip install --pre ipython[all]
python setup.py install
pip install numpy # For the full examples
```

**Comment by rgbkrk** [comment]
Included some installation instructions in bcf64bcc5198d8484035058608e9fcc080077633. Let me know if this is satisfactory and we'll close the issue.

On IPython's end, we need the nbextensions experience to get a bit better as well (that's on me and @jdfreder).

**Comment by rgbkrk** [comment]
Wow, I see what happens when numpy isn't installed.

```
/Users/kyle6475/.virtualenvs/bitty/lib/python3.4/site-packages/IPython/utils/traitlets.py in __init__(self, klass, args, kw, allow_none, **metadata)
    937         else:
    938             raise TraitError('The klass attribute must be a class'
--> 939                                 ' not: %r' % klass)
    940 
    941         # self.klass is a class, so handle default_value

TraitError: The klass attribute must be a class not: None
```

I'll fix that up too.

**Comment by rgbkrk** [comment]
Ok, fixed the lack-of-numpy issue.

You can also `pip install bitjet` now!

**Comment by xspager** [comment]
Tried in a new virtualenv and the example worked after installing numpy. Good to know it works with pip now :)

**Comment by jdfreder** [comment]
Now that this is pip-able, I think we can close this.
